from turtle import *
import turtle

setup(750,600)
bgcolor("white")

def dibuja_dino(velocidad):
    pl = turtle.Turtle()
    pl.speed(velocidad)
    pl.pensize(4)
    pl.fillcolor("green")
    pl.pencolor("green")
    pl.begin_fill()
    pl.left(90)
    pl.forward(150)
    pl.left(-120)
    pl.forward(100)
    pl.right(-90)
    pl.forward(80)
    pl.left(90)
    pl.forward(90)
    pl.left(30)
    pl.forward(60)
    pl.left(40)
    pl.forward(80)
    pl.left(50)
    pl.forward(70)
    pl.right(50)
    pl.forward(120)
    pl.right(40)
    pl.forward(80)
    pl.right(50)
    pl.forward(90)
    pl.left(140)
    pl.forward(70)
    pl.left(90)
    pl.forward(60)
    pl.right(90)
    pl.forward(70)
    pl.left(90)
    pl.forward(70)
    pl.right(45)
    pl.forward(120)
    pl.right(135)
    pl.forward(90)
    pl.left(145)
    pl.forward(90)
    pl.left(35)
    pl.forward(90)
    pl.left(145)
    pl.forward(93)
    pl.right(110)
    pl.forward(110)
    pl.left(55)
    pl.forward(100)
    pl.right(90)
    pl.forward(80)
    pl.right(90)
    pl.forward(70)
    pl.right(130)
    pl.forward(110)
    pl.end_fill()

def dibuja_bordes(velocidad):
    pl = turtle.Turtle()
    pl.speed(velocidad)
    pl.pensize(50)
    pl.penup()
    pl.left(90)
    pl.backward(190)
    pl.left(90)
    pl.backward(30)
    pl.pendown()
    pl.left(180)
    pl.forward(120)
    pl.right(90)
    pl.backward(270)
    pl.penup()
    pl.right(180)
    pl.forward(180)
    pl.right(90)
    pl.backward(190)
    pl.pendown()
    pl.right(180)
    pl.forward(260)
    pl.left(90)
    pl.forward(140)
    pl.penup()
    pl.left(180)
    pl.backward(140)
    pl.pendown()
    pl.right(180)
    pl.forward(170)
    pl.left(90)
    pl.forward(120)

dibuja_dino(6)
dibuja_bordes(5)
turtle.exitonclick()